### ISSUE TITLE
Guardar información asociada a stripe

### ISSUE THREAD

**Issue by a8081** [Proyecto-FIS/users#19]
Hay que añadir un atributo adicional al objeto Customer, que se llame _**stripe_id**_. Suponiendo que el nuevo customer se llame _**new_customer**_ 
```
const stripe = require('stripe')(process.env.STRIPE_PUBLIC_KEY);

// Guardo en customer el objeto que devuelve stripe
const stripe_customer = await stripe.customers.create({
            name: new_customer.name,
            email: new_customer.email
          });
```
Y el nuevo atributo tomaría el siguiente valor:
```
stripe_id = stripe_customer.id
```
Simplemente meter esto en el create de customer para que se almacene la información correspondiente en stripe.

Para utilizar stripe: _npm install stripe_

**Comment by ArturoPerezSanchez** [comment]
Atributo y variable de entorno añadidas
